name: buildwheels

on:
  pull_request:
    branches: [ main ]

jobs:
  debug_build_ok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # https://github.com/pypa/setuptools_scm/issues/480
      - run: DEBUG=1 VERBOSE=1 pip install --verbose -e .[tests]
      - run: pytest -v -s -We -p no:unraisableexception tests

  zenodo_json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: notiz-dev/github-action-json-property@release
        with: 
          path: '.zenodo.json'
          prop_path: 'creators'

  build_wheels:
    needs: [debug_build_ok, zenodo_json]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: >-
            mingw-w64-x86_64-gcc-fortran
            mingw-w64-x86_64-ninja
            m4
      
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.2

      - name: Build and test wheels
        env:
          CIBW_SKIP: "*-win32 *-manylinux_i686 pp* *musllinux*"
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_ARGS="-DCMAKE_MAKE_PROGRAM=D:/a/_temp/msys64/mingw64/bin/ninja.exe" CMAKE_PROGRAM_PATH="D:/a/_temp/msys64/usr/bin" CMAKE_GENERATOR="Ninja" TEMP="D:/a/_temp/"
          CIBW_BEFORE_BUILD_MACOS: brew reinstall gcc
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=`sw_vers -productVersion` SYSTEM_VERSION_COMPAT=0
          CIBW_BEFORE_TEST: python -m pip debug --verbose
          CIBW_TEST_REQUIRES: pytest pytest-order
          CIBW_TEST_COMMAND: pytest -v -s -We -p no:unraisableexception {package}/tests
        run: python -m cibuildwheel --output-dir dist

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{matrix.os}}-${{matrix.manylinux}}
          path: dist

