name: forlint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
   lint:
      steps:
         - uses: actions/checkout@v2
         - uses: NOAA-GFDL/simple-lint@v1
           with:
             failure: true
             ftn_line_length: 100
