name: tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  build:
    strategy:
      matrix:
        #platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [windows-latest]
        python-version: ["3.7"] #, "3.10"]
    runs-on: ${{ matrix.platform }}
    steps:
      - if: matrix.platform == 'macos-latest'
        run: brew reinstall gcc

      - if: matrix.platform == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: >-
            mingw-w64-x86_64-gcc-fortran

      - if: matrix.platform == 'windows-latest'
        run: echo CMAKE_ARGS="-DCMAKE_Fortran_COMPILER=D:/a/_temp/msys64/mingw64/bin/gfortran.exe" >> $GITHUB_ENV
        run: echo CMAKE_GENERATOR="Ninja" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -e .

      # sanity check if we do not depend on something from test-time-requirements.txt
      - run: python -We -c "import PyPartMC"

      - run: pip install -r test-time-requirements.txt

      # ensure previous pip did not overwrite the package
      - run: pip install -e .

      - run: pytest -p no:unraisableexception -We tests

