name: tests

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 13 * * 4'

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] #, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get install libnetcdff-dev
  
      - if: matrix.platform == 'macos-latest'
        run: brew reinstall netcdf gcc

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install -e .

      # sanity check if we do not depend on something from test-time-requirements.txt
      - run: python -We -c "import PyPartMC"

      - run: pip install -r test-time-requirements.txt

      # ensure previous pip did not overwrite the package
      - run: pip install -e .

      - run: pytest -p no:unraisableexception -We tests

